# Damn Vulnerable NodeJS Application
# https://github.com/appsecco/dvna

FROM node:10.24-stretch
LABEL MAINTAINER "Subash SN"

WORKDIR /app

RUN npm install -g nodemon

CMD ["/bin/bash", "/app/entrypoint-dev.sh"]
